# -*- coding: utf-8 -*-
"""Gearbox failure deployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KpvEddCJJhU0e1QMEmdtvXhkE8RNJ563
"""

!pip install streamlit

import numpy as np
import joblib
import streamlit as st

model = joblib.load('gearbox_failure_prediction.pkl')

st.set_page_config(page_title='Gearbox Failure predication',layout='centered')
st.title("Gearbox Failure predication App")
st.write("predict whether the is gearbox get fail using different properties")
load = st.number_input(" value of load",value=None)
Temperature = st.number_input(" value of Temperature",value=None)
vibration =st.number_input(" value of vibration",value=None)
oil_level = st.number_input(" value of oil_level",value=None)

if st.button("Predict"):
  input_data = np.array([[]])
  predication = model.predict(input_data)
  if predication == 1 :
    st.success("** pass**")
  else:
    st.error("**fail**")